### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by zzehli** [bradtraversy/wildfire-tracker#2]
I have this warning in my browser when I run the finished app. I try to debug but I can't find `map` method in `LocationMarker` or elsewhere.
```
0.chunk.js:35649 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Map`. See https://reactjs.org/link/warning-keys for more information.
    at LocationMarker (http://localhost:3000/static/js/main.chunk.js:614:3)
    at Map (http://localhost:3000/static/js/main.chunk.js:748:3)
    at div
    at App (http://localhost:3000/static/js/main.chunk.js:57:91)
```

**Comment by zzehli** [comment]
This is solved by adding the `index` parameter in `LocationMarker` in [this merge](https://github.com/bradtraversy/wildfire-tracker/commit/6346dd8539a324c53eef0e97f91a91eb4832cfdf)
